## numpy 基础结构

In [ ]:
from numpy import *

In [11]:
import numpy as np

In [12]:
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Ndarray 对象

In [185]:
x = np.array([[100,2,3],[4,5,6]], dtype='i2') #np.array(object, dtype=None, copy=True, order=None,subok = False, ndim=0)
x

array([[[100,   2,   3],
        [  4,   5,   6]]], dtype=int16)

In [187]:
y = array([1,2,3,'c'])  

In [188]:
y

array(['1', '2', '3', 'c'], dtype='<U21')

In [189]:
x.ndim #维度 

3

In [58]:
x.dtype #Numpy 数据类型：bool int int 8 int 16 int 32 int 64 float float 16 float 32 float 64 complex

dtype('int16')

## dtype对象

In [38]:
dt = np.dtype(np.int8)

In [39]:
dt

dtype('int8')

In [60]:
dt = np.dtype('i1')

In [61]:
dt

dtype('int8')

## dtype 自定义

In [63]:
dt = np.dtype([('age',np.int8)])

In [64]:
dt

dtype([('age', 'i1')])

In [65]:
a = np.array([(10,),(20,),(30,)], dtype = dt)

In [66]:
a

array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

### student 结构体

In [67]:
student = np.dtype([('name', 'S20'),('age','i1'),("marks",'f4')])
student

dtype([('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [68]:
a = np.array([('abd',21,12),('xyu',20,89),('kas',32,88)], dtype = student)

In [69]:
a

array([(b'abd', 21, 12.), (b'xyu', 20, 89.), (b'kas', 32, 88.)],
      dtype=[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

## Numpy 的 array属性

In [70]:
'''
axis 秩
[] 1
[[]] 2
..
[[[]]]

axis = 0
'''

'\naxis 秩\n[] 1\n[[]] 2\n..\n[[[]]]\n\naxis = 0\n'

#### 1) ndarray.ndim

In [71]:
a = np.arange(48) 

In [72]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [73]:
a.ndim

1

In [74]:
b = a.reshape(2,-1)

In [75]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
        40, 41, 42, 43, 44, 45, 46, 47]])

In [76]:
b.ndim

2

#### 2) ndarray.shape

In [78]:
a = np.array([[1,2,3],[4,5,6]])

In [79]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
a.shape

(2, 3)

In [81]:
a.shape = (3,2) #修改方式一

In [82]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
a.shape = (3,-1) # 3行 几列我不管 = -1

In [86]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
a.shape = (-1, 3)

In [88]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
a = a.reshape(3,2) #修改方式二

In [92]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

#### 3) ndarray.itemsize

In [94]:
x = np.array([1,2,3,4,5],dtype = np.int8)

In [95]:
x.itemsize

1

In [96]:
x = np.array([1,2,3,4,5],dtype = np.int16)

In [97]:
x.itemsize

2

In [100]:
x = np.array([1,2,3,4,5,5,76,765,756,568],dtype = np.int32) #内存 16 16bits -> 2B  int16 -> 2 int8 -> 1 int32 -> 4

In [101]:
x.itemsize

4

## 创建数组

#### 1)np.empty(shape, dtype=..)

In [104]:
x = np.empty([2,3], dtype=int) #empty 不代表 0 填充 - 而是一个初始化的数组，值=随机数

In [105]:
x

array([[ 4611686018427387904, -1152912732737719633,                    3],
       [                   0,                    0,      844424930131968]])

#### 2) zeros 

In [107]:
x = np.zeros(5)

In [108]:
x

array([0., 0., 0., 0., 0.])

In [109]:
x = np.zeros((5), dtype = int)

In [110]:
x

array([0, 0, 0, 0, 0])

In [115]:
y = np.zeros((2,2), dtype=[('x','i4'),('y','i4'),('z','i4')])

In [116]:
y

array([[(0, 0, 0), (0, 0, 0)],
       [(0, 0, 0), (0, 0, 0)]],
      dtype=[('x', '<i4'), ('y', '<i4'), ('z', '<i4')])

#### 3) ones

In [117]:
 x = np.ones(5)

In [118]:
x

array([1., 1., 1., 1., 1.])

In [123]:
x = np.ones([2,2])#,dtype =[('x','i4'),('y','i4'),('z','i4')])

In [124]:
x

array([[1., 1.],
       [1., 1.]])

## 利用范围创建数组

#### 1)  numpy.arange(start, stop, step, dtype)

In [125]:
x = np.arange(5)

In [126]:
x

array([0, 1, 2, 3, 4])

In [127]:
x = np.arange(5, dtype=float)

In [129]:
x

array([0., 1., 2., 3., 4.])

In [130]:
x = np.arange(10,20,2)

In [131]:
x

array([10, 12, 14, 16, 18])

#### 2) numpy.linspace

In [132]:
# start stop num = 50 endpoint=True retstep=间距默认False dtype =类型

In [133]:
a = np.linspace(1,60)

In [134]:
a

array([ 1.        ,  2.20408163,  3.40816327,  4.6122449 ,  5.81632653,
        7.02040816,  8.2244898 ,  9.42857143, 10.63265306, 11.83673469,
       13.04081633, 14.24489796, 15.44897959, 16.65306122, 17.85714286,
       19.06122449, 20.26530612, 21.46938776, 22.67346939, 23.87755102,
       25.08163265, 26.28571429, 27.48979592, 28.69387755, 29.89795918,
       31.10204082, 32.30612245, 33.51020408, 34.71428571, 35.91836735,
       37.12244898, 38.32653061, 39.53061224, 40.73469388, 41.93877551,
       43.14285714, 44.34693878, 45.55102041, 46.75510204, 47.95918367,
       49.16326531, 50.36734694, 51.57142857, 52.7755102 , 53.97959184,
       55.18367347, 56.3877551 , 57.59183673, 58.79591837, 60.        ])

In [149]:
a = np.linspace(1,60, num=10).reshape([2,-1])

In [150]:
a

array([[ 1.        ,  7.55555556, 14.11111111, 20.66666667, 27.22222222],
       [33.77777778, 40.33333333, 46.88888889, 53.44444444, 60.        ]])

In [151]:
a = np.linspace(1,60, num=10, endpoint =False).reshape([2,-1])

In [152]:
a

array([[ 1. ,  6.9, 12.8, 18.7, 24.6],
       [30.5, 36.4, 42.3, 48.2, 54.1]])

In [139]:
a = np.linspace(1,60, num=10, endpoint =False, retstep=False)

In [140]:
a

array([ 1. ,  6.9, 12.8, 18.7, 24.6, 30.5, 36.4, 42.3, 48.2, 54.1])

In [141]:
a = np.linspace(1,60, num=10, endpoint =False, retstep=True)

In [142]:
a #等差 q=5.9

(array([ 1. ,  6.9, 12.8, 18.7, 24.6, 30.5, 36.4, 42.3, 48.2, 54.1]), 5.9)

In [143]:
a = np.linspace(1,60, num=10, endpoint =False, retstep=True, dtype=int)

In [144]:
a

(array([ 1,  6, 12, 18, 24, 30, 36, 42, 48, 54]), 5.9)

In [159]:
a = np.linspace(1,60, num=10, endpoint =False, dtype=int).reshape([5,-1])

In [160]:
a

array([[ 1,  6],
       [12, 18],
       [24, 30],
       [36, 42],
       [48, 54]])

#### 3) numpy.logspace

In [161]:
# start stop num endpoint = True base dtype

In [162]:
a = np.logspace(1,2) # 10^1 10^2

In [163]:
a

array([ 10.        ,  10.48113134,  10.98541142,  11.51395399,
        12.06792641,  12.64855217,  13.25711366,  13.89495494,
        14.56348478,  15.26417967,  15.9985872 ,  16.76832937,
        17.57510625,  18.42069969,  19.30697729,  20.23589648,
        21.20950888,  22.22996483,  23.29951811,  24.42053095,
        25.59547923,  26.82695795,  28.11768698,  29.47051703,
        30.88843596,  32.37457543,  33.93221772,  35.56480306,
        37.2759372 ,  39.06939937,  40.94915062,  42.9193426 ,
        44.98432669,  47.14866363,  49.41713361,  51.79474679,
        54.28675439,  56.89866029,  59.63623317,  62.50551925,
        65.51285569,  68.6648845 ,  71.9685673 ,  75.43120063,
        79.06043211,  82.86427729,  86.85113738,  91.0298178 ,
        95.40954763, 100.        ])

In [166]:
a = np.logspace(1,2, base = 2, num=5) #2^1 2^2

In [167]:
a

array([2.        , 2.37841423, 2.82842712, 3.36358566, 4.        ])

## Numpy 的线性代数

#### 1) dot 乘

In [171]:
a = np.array([[1,2],[3,4]])

In [172]:
a

array([[1, 2],
       [3, 4]])

In [173]:
b = np.array([[4,5],[6,7]])

In [174]:
b

array([[4, 5],
       [6, 7]])

In [175]:
np.dot(a,b)

array([[16, 19],
       [36, 43]])

In [176]:
np.dot(b,a)

array([[19, 28],
       [27, 40]])

#### 2) Solve方程解

In [177]:
a = np.array([[1,1,1],[0,2,5],[2,5,-1]])

In [178]:
a

array([[ 1,  1,  1],
       [ 0,  2,  5],
       [ 2,  5, -1]])

In [179]:
b = np.array([6,-4,27])

In [180]:
b

array([ 6, -4, 27])

In [181]:
np.linalg.solve(a,b)

array([ 5.,  3., -2.])