In [119]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [120]:
iris = datasets.load_iris()
x = iris.data

In [121]:
y = iris.target

In [122]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [123]:
## 算法验证

In [124]:
kNN_classifier = KNeighborsClassifier(n_neighbors = 5)

In [125]:
kNN_classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [126]:
y_predict = kNN_classifier.predict(x_test) #已经有 y_test 答案 ，要知道 kNN 的答案是什么

In [127]:
y_predict

array([0, 1, 0, 1, 2, 2, 1, 0, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 0, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 1])

In [128]:
y_test

array([0, 1, 0, 1, 1, 2, 1, 0, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 0, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 1])

In [129]:
sum(y_predict == y_test)

29

In [130]:
sum(y_predict == y_test) / len(y_test) 

0.9666666666666667

NameError: name 'KNNClassifier' is not defined

In [132]:
x[0]

array([5.1, 3.5, 1.4, 0.2])

In [151]:
a = np.array([[1.2, 4.5, 0.4, 0.2]])

In [152]:
y_predict = kNN_classifier.predict(a)

In [153]:
y_predict[0]

0